"""In-play evidence contract v1 (#122): book reconstruction, game state and coverage. Pure.

This module turns journalled in-play messages into evidence that later code may rely on. It
never opens a connection: the only transport is `read_journal`, which reads a local JSONL
file (a fixture, or a journal a future, separately approved recorder wrote). Importing it,
rendering a dashboard with it or running its tests makes no network call.

**Order books (snapshot plus delta).** Kalshi's orderbook channel "Sends orderbook_snapshot
first, then incremental orderbook_delta updates", and each message carries `seq`, a
"Sequential number that should be checked if you want to guarantee you received all the
messages" (docs.kalshi.com/websockets/orderbook-updates, read 2026-09-28). The reconstruction
rules are:

- **Valid start.** Nothing is usable until a snapshot with a sequence number arrives. A delta
  before it is ignored and counted, never applied to an empty book.
- **Sequence.** A delta applies only when its `seq` is exactly one past the last applied one on
  the same subscription (`sid`).
- **Duplicates** (`seq` at or below the last applied one) are ignored and counted.
- **Gaps and out-of-order arrivals** (`seq` more than one ahead, or another `sid`) make the book
  UNUSABLE until a new snapshot. v1 keeps no reorder buffer: a late message after a gap does
  not repair the book; only a snapshot does (fail closed).
- **Invalid results** (a level driven below zero, a crossed book) are UNUSABLE until resync.
- Unusable is a state, not an error, and it is retained: the coverage report counts it.

**Timestamps** are kept apart and never substituted for one another (`ClockKind`):
- `source_ts_utc`: the venue's own stamp (`ts_ms`), when it sent one;
- `first_observed_utc`: when we first saw this content;
- `receipt_utc`: when this copy arrived;
- `processing_utc`: when it was normalized here.

A game clock ("Q4 02:13") is not a UTC time and is kept as text.

**Game state.** Observations are appended, never overwritten. A corrected play (an overturned
touchdown) is a new observation linked to the one it corrects, so `game_state_as_of` shows what
we had actually seen at each instant: the provisional score before the correction arrived, the
corrected one after. The Kalshi `game_stats` schema does not enumerate its fields
(docs.kalshi.com/api-reference/live-data/get-game-stats, read 2026-09-28): every field here is
optional and UNKNOWN (None) unless the source supplied it, and a null response is
UNSUPPORTED_OR_UNMAPPED, not an empty game.

**Failures are evidence.** Connection losses, HTTP 429s, parse errors, gaps and resyncs are
journalled beside the data and appear in `coverage_report`. A window with no usable book is
reported as such, never dropped.

Nothing here prices, sizes or submits anything. Synthetic fixtures are labelled synthetic.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field, replace
from datetime import datetime, timedelta, timezone
from decimal import Decimal, InvalidOperation
from enum import Enum
from pathlib import Path
from typing import Any, Iterable, Iterator, Mapping, Sequence

from .fee_schedules import valid_price
from .freshness import parse_utc
from .opportunity import DepthLadder, DepthLevel, DepthStatus, OutcomeFinality, walk_ladder

CONTRACT_VERSION = "inplay-evidence-v1"
QUANTITY_STEP = Decimal("0.01")  # Kalshi fixed-point counts (docs: 0-2 decimals, minimum 0.01)
BOOK_SIDES = ("yes", "no")


class DataKind(str, Enum):
    """Where evidence came from. SYNTHETIC and FIXTURE may never be labelled LIVE."""

    SYNTHETIC = "SYNTHETIC"  # generated by code in this repository
    FIXTURE = "FIXTURE"  # hand-written test input shaped like the documented messages
    RECORDED = "RECORDED"  # written by an approved recorder (none exists yet)


# --------------------------------------------------------------------------- clocks


@dataclass(frozen=True)
class Stamps:
    """The four clocks of one message. None is unknown and is never filled in from another."""

    receipt_utc: str
    first_observed_utc: str
    processing_utc: str | None = None
    source_ts_utc: str | None = None

    def __post_init__(self) -> None:
        received, first = parse_utc(self.receipt_utc), parse_utc(self.first_observed_utc)
        if received is None or first is None:
            raise ValueError("receipt and first-observed times must be timezone-aware")
        if first > received:
            raise ValueError("first observation cannot be later than this copy's receipt")
        for name in ("processing_utc", "source_ts_utc"):
            value = getattr(self, name)
            if value is not None and parse_utc(value) is None:
                raise ValueError(f"{name} must be timezone-aware or None")


def _ms_to_utc(value: Any) -> str | None:
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        return None
    return datetime.fromtimestamp(value / 1000, tz=timezone.utc).isoformat()


def _sha(obj: Any) -> str:
    return hashlib.sha256(json.dumps(obj, sort_keys=True, separators=(",", ":"), default=str).encode()).hexdigest()


# --------------------------------------------------------------------------- book messages


class MessageKind(str, Enum):
    SNAPSHOT = "SNAPSHOT"
    DELTA = "DELTA"


@dataclass(frozen=True)
class BookMessage:
    """One normalized order-book message. Levels are bids: (price in dollars, contracts)."""

    kind: MessageKind
    market_ticker: str
    sid: int | None
    seq: int | None
    stamps: Stamps
    raw_sha256: str
    yes_bids: tuple[tuple[Decimal, Decimal], ...] = ()  # SNAPSHOT only
    no_bids: tuple[tuple[Decimal, Decimal], ...] = ()
    side: str | None = None  # DELTA only: "yes" | "no"
    price: Decimal | None = None
    delta: Decimal | None = None


@dataclass(frozen=True)
class ParseFailure:
    reason: str
    detail: str
    receipt_utc: str
    raw_sha256: str


def _dec(value: Any) -> Decimal:
    try:
        out = Decimal(str(value))
    except (InvalidOperation, ValueError):
        raise ValueError(f"not a number: {value!r}") from None
    if not out.is_finite():
        raise ValueError(f"not finite: {value!r}")
    return out


def _count(value: Any, *, signed: bool) -> Decimal:
    out = _dec(value)
    if out % QUANTITY_STEP != 0:
        raise ValueError(f"count {out} is off the 0.01 contract step")
    if not signed and out < 0:
        raise ValueError(f"negative count {out}")
    return out


def _price(value: Any) -> Decimal:
    out = _dec(value)
    if not valid_price(out):
        raise ValueError(f"price {value!r} is not a dollar price strictly inside (0, 1) on the 1/100-cent grid")
    return out


def _levels(raw: Any) -> tuple[tuple[Decimal, Decimal], ...]:
    if raw is None:
        return ()
    if not isinstance(raw, list):
        raise ValueError("book side is not a list")
    out: dict[Decimal, Decimal] = {}
    for level in raw:
        if not isinstance(level, (list, tuple)) or len(level) != 2:
            raise ValueError(f"malformed level {level!r}")
        price, size = _price(level[0]), _count(level[1], signed=False)
        if size > 0:
            out[price] = out.get(price, Decimal(0)) + size
    return tuple(sorted(out.items()))


def parse_book_message(raw: Mapping[str, Any], *, receipt_utc: str, first_observed_utc: str | None = None,
                       processing_utc: str | None = None) -> BookMessage | ParseFailure:
    """Normalize one Kalshi websocket orderbook message as documented on 2026-09-28.

    Snapshot: `{"type": "orderbook_snapshot", "sid", "seq", "msg": {"market_ticker",
    "yes_dollars_fp": [[price, count]], "no_dollars_fp": [...]}}`. Delta: `{"type":
    "orderbook_delta", "sid", "seq", "msg": {"market_ticker", "price_dollars", "delta_fp", "side",
    "ts_ms"}}`. Prices are dollar strings ("0.4200"), counts fixed-point strings. Anything else,
    including a price in cents, is a `ParseFailure` that is kept, never a guess."""
    digest = _sha(raw)
    if parse_utc(receipt_utc) is None:
        raise ValueError("receipt_utc must be timezone-aware")

    def fail(reason: str, detail: str) -> ParseFailure:
        return ParseFailure(reason, detail, receipt_utc, digest)

    if not isinstance(raw, Mapping):
        return fail("NOT_AN_OBJECT", type(raw).__name__)
    kind = {"orderbook_snapshot": MessageKind.SNAPSHOT, "orderbook_delta": MessageKind.DELTA}.get(raw.get("type"))
    if kind is None:
        return fail("UNKNOWN_TYPE", str(raw.get("type")))
    body = raw.get("msg")
    if not isinstance(body, Mapping) or not isinstance(body.get("market_ticker"), str) or not body["market_ticker"]:
        return fail("NO_MARKET", "msg.market_ticker is missing")
    sid, seq = raw.get("sid"), raw.get("seq")
    sid = sid if isinstance(sid, int) and not isinstance(sid, bool) else None
    seq = seq if isinstance(seq, int) and not isinstance(seq, bool) and seq >= 0 else None
    stamps = Stamps(receipt_utc=receipt_utc, first_observed_utc=first_observed_utc or receipt_utc,
                    processing_utc=processing_utc, source_ts_utc=_ms_to_utc(body.get("ts_ms")))
    try:
        if kind is MessageKind.SNAPSHOT:
            return BookMessage(kind, body["market_ticker"], sid, seq, stamps, digest,
                               yes_bids=_levels(body.get("yes_dollars_fp")), no_bids=_levels(body.get("no_dollars_fp")))
        side = body.get("side")
        if side not in BOOK_SIDES:
            return fail("BAD_SIDE", repr(side))
        delta = _count(body.get("delta_fp"), signed=True)
        if delta == 0:
            return fail("ZERO_DELTA", "a delta of 0 contracts changes nothing and is not documented")
        return BookMessage(kind, body["market_ticker"], sid, seq, stamps, digest, side=side,
                           price=_price(body.get("price_dollars")), delta=delta)
    except ValueError as exc:
        return fail("BAD_VALUE", str(exc))


# --------------------------------------------------------------------------- reconstruction


class BookStatus(str, Enum):
    NO_VALID_START = "NO_VALID_START"  # no snapshot yet: unusable
    VALID = "VALID"
    GAP_AWAITING_RESYNC = "GAP_AWAITING_RESYNC"  # a sequence gap or a foreign sid: unusable until a snapshot
    INVALID_AWAITING_RESYNC = "INVALID_AWAITING_RESYNC"  # negative level or crossed book: unusable


UNUSABLE = frozenset({BookStatus.NO_VALID_START, BookStatus.GAP_AWAITING_RESYNC, BookStatus.INVALID_AWAITING_RESYNC})


class Applied(str, Enum):
    SNAPSHOT_APPLIED = "SNAPSHOT_APPLIED"
    RESYNCED = "RESYNCED"  # a snapshot that ended an unusable period
    DELTA_APPLIED = "DELTA_APPLIED"
    IGNORED_BEFORE_START = "IGNORED_BEFORE_START"
    IGNORED_DUPLICATE = "IGNORED_DUPLICATE"
    IGNORED_WHILE_UNUSABLE = "IGNORED_WHILE_UNUSABLE"
    GAP_DETECTED = "GAP_DETECTED"
    SNAPSHOT_WITHOUT_SEQ = "SNAPSHOT_WITHOUT_SEQ"
    DELTA_WITHOUT_SEQ = "DELTA_WITHOUT_SEQ"
    NEGATIVE_LEVEL = "NEGATIVE_LEVEL"
    CROSSED_BOOK = "CROSSED_BOOK"
    WRONG_MARKET = "WRONG_MARKET"


@dataclass(frozen=True)
class BookState:
    """The reconstructed book of one market, after the messages applied so far."""

    market_ticker: str
    status: BookStatus = BookStatus.NO_VALID_START
    sid: int | None = None
    last_seq: int | None = None
    yes_bids: tuple[tuple[Decimal, Decimal], ...] = ()
    no_bids: tuple[tuple[Decimal, Decimal], ...] = ()
    valid_since_utc: str | None = None  # receipt of the snapshot that started the valid period
    last_receipt_utc: str | None = None  # the last message that touched this book, whatever it did
    last_applied_receipt_utc: str | None = None
    last_source_ts_utc: str | None = None
    counts: tuple[tuple[str, int], ...] = ()

    @property
    def usable(self) -> bool:
        return self.status is BookStatus.VALID

    def count(self, what: Applied) -> int:
        return dict(self.counts).get(what.value, 0)

    def best_yes_bid(self) -> tuple[Decimal, Decimal] | None:
        return self.yes_bids[-1] if self.usable and self.yes_bids else None

    def best_no_bid(self) -> tuple[Decimal, Decimal] | None:
        return self.no_bids[-1] if self.usable and self.no_bids else None


@dataclass(frozen=True)
class Transition:
    state: BookState
    applied: Applied
    detail: str


def _bump(counts: tuple[tuple[str, int], ...], what: Applied) -> tuple[tuple[str, int], ...]:
    d = dict(counts)
    d[what.value] = d.get(what.value, 0) + 1
    return tuple(sorted(d.items()))


def _crossed(yes: Sequence[tuple[Decimal, Decimal]], no: Sequence[tuple[Decimal, Decimal]]) -> bool:
    return bool(yes and no and yes[-1][0] + no[-1][0] >= 1)


def apply_message(state: BookState, msg: BookMessage) -> Transition:
    """The book after `msg`. Pure: `state` is not changed."""
    seen = replace(state, last_receipt_utc=msg.stamps.receipt_utc)

    def done(new: BookState, what: Applied, detail: str) -> Transition:
        return Transition(replace(new, counts=_bump(new.counts, what)), what, detail)

    if msg.market_ticker != state.market_ticker:
        return done(replace(state), Applied.WRONG_MARKET, f"{msg.market_ticker} is not {state.market_ticker}")
    if msg.kind is MessageKind.SNAPSHOT:
        if msg.seq is None or msg.sid is None:
            return done(replace(seen, status=BookStatus.GAP_AWAITING_RESYNC), Applied.SNAPSHOT_WITHOUT_SEQ,
                        "a snapshot without sid/seq cannot start a sequenced book")
        was_unusable = state.status is not BookStatus.VALID and state.status is not BookStatus.NO_VALID_START
        new = replace(seen, sid=msg.sid, last_seq=msg.seq, yes_bids=msg.yes_bids, no_bids=msg.no_bids,
                      valid_since_utc=msg.stamps.receipt_utc, last_applied_receipt_utc=msg.stamps.receipt_utc,
                      last_source_ts_utc=msg.stamps.source_ts_utc or state.last_source_ts_utc)
        if _crossed(msg.yes_bids, msg.no_bids):
            return done(replace(new, status=BookStatus.INVALID_AWAITING_RESYNC, valid_since_utc=None),
                        Applied.CROSSED_BOOK, "snapshot is crossed: best yes bid + best no bid >= 1")
        return done(replace(new, status=BookStatus.VALID),
                    Applied.RESYNCED if was_unusable else Applied.SNAPSHOT_APPLIED, f"sid {msg.sid} seq {msg.seq}")
    # delta
    if state.status is BookStatus.NO_VALID_START:
        return done(seen, Applied.IGNORED_BEFORE_START, "no snapshot yet")
    if state.status is not BookStatus.VALID:
        return done(seen, Applied.IGNORED_WHILE_UNUSABLE, f"book is {state.status.value}")
    if msg.seq is None:
        return done(replace(seen, status=BookStatus.GAP_AWAITING_RESYNC, valid_since_utc=None),
                    Applied.DELTA_WITHOUT_SEQ, "a delta without seq cannot be ordered")
    if msg.sid != state.sid:
        return done(replace(seen, status=BookStatus.GAP_AWAITING_RESYNC, valid_since_utc=None), Applied.GAP_DETECTED,
                    f"delta from sid {msg.sid}, book is sid {state.sid}")
    if msg.seq <= state.last_seq:
        return done(seen, Applied.IGNORED_DUPLICATE, f"seq {msg.seq} <= last applied {state.last_seq}")
    if msg.seq != state.last_seq + 1:
        return done(replace(seen, status=BookStatus.GAP_AWAITING_RESYNC, valid_since_utc=None), Applied.GAP_DETECTED,
                    f"expected seq {state.last_seq + 1}, got {msg.seq}")
    levels = dict(state.yes_bids if msg.side == "yes" else state.no_bids)
    size = levels.get(msg.price, Decimal(0)) + msg.delta
    if size < 0:
        return done(replace(seen, status=BookStatus.INVALID_AWAITING_RESYNC, valid_since_utc=None, last_seq=msg.seq),
                    Applied.NEGATIVE_LEVEL, f"{msg.side} {msg.price} would hold {size}")
    if size == 0:
        levels.pop(msg.price, None)
    else:
        levels[msg.price] = size
    side_levels = tuple(sorted(levels.items()))
    yes = side_levels if msg.side == "yes" else state.yes_bids
    no = side_levels if msg.side == "no" else state.no_bids
    new = replace(seen, last_seq=msg.seq, yes_bids=yes, no_bids=no, last_applied_receipt_utc=msg.stamps.receipt_utc,
                  last_source_ts_utc=msg.stamps.source_ts_utc or state.last_source_ts_utc)
    if _crossed(yes, no):
        return done(replace(new, status=BookStatus.INVALID_AWAITING_RESYNC, valid_since_utc=None), Applied.CROSSED_BOOK,
                    "delta crossed the book")
    return done(new, Applied.DELTA_APPLIED, f"seq {msg.seq}")


def reconstruct(market_ticker: str, messages: Iterable[BookMessage]) -> tuple[BookState, tuple[Transition, ...]]:
    """Apply `messages` in arrival order; return the final state and every transition."""
    state, out = BookState(market_ticker), []
    for msg in messages:
        t = apply_message(state, msg)
        out.append(t)
        state = t.state
    return state, tuple(out)


# --------------------------------------------------------------------------- REST snapshots (route B)


@dataclass(frozen=True)
class RestSnapshot:
    """One polled REST order book. It has no sequence number and no venue timestamp
    (docs: the orderbook response schema carries neither), so each poll stands alone and
    nothing between two polls is known."""

    market_ticker: str
    yes_bids: tuple[tuple[Decimal, Decimal], ...]
    no_bids: tuple[tuple[Decimal, Decimal], ...]
    stamps: Stamps
    depth_limit: int | None  # the `depth` requested; None = all levels
    raw_sha256: str
    anomaly: str | None = None

    @property
    def truncated_yes(self) -> bool:
        return self.depth_limit is not None and len(self.yes_bids) >= self.depth_limit


def rest_snapshot(market_ticker: str, payload: Mapping[str, Any], *, receipt_utc: str, depth_limit: int | None,
                  first_observed_utc: str | None = None) -> RestSnapshot:
    """Normalize `GET /markets/{ticker}/orderbook` (`{"orderbook_fp": {"yes_dollars", "no_dollars"}}`).
    A malformed or crossed book keeps `anomaly` and no levels; it is never repaired."""
    stamps = Stamps(receipt_utc=receipt_utc, first_observed_utc=first_observed_utc or receipt_utc)
    book = payload.get("orderbook_fp") if isinstance(payload, Mapping) else None
    digest = _sha(payload)
    if not isinstance(book, Mapping):
        return RestSnapshot(market_ticker, (), (), stamps, depth_limit, digest, "NO_BOOK")
    try:
        yes, no = _levels(book.get("yes_dollars")), _levels(book.get("no_dollars"))
    except ValueError as exc:
        return RestSnapshot(market_ticker, (), (), stamps, depth_limit, digest, f"MALFORMED: {exc}")
    if _crossed(yes, no):
        return RestSnapshot(market_ticker, (), (), stamps, depth_limit, digest, "CROSSED")
    return RestSnapshot(market_ticker, yes, no, stamps, depth_limit, digest)


# --------------------------------------------------------------------------- selling into the bids


@dataclass(frozen=True)
class SaleWalk:
    """What selling `quantity` contracts of one side into its bids would receive, before fees.

    Built on `opportunity.walk_ladder`: selling YES into YES bids at b is the mirror of taking
    NO asks at 1 - b, so the walk reuses the canonical depth walk and never prices a partial
    fill by accident. `levels` are (sale price, size) from the best bid down."""

    status: DepthStatus
    quantity: Decimal
    available: Decimal | None
    levels: tuple[tuple[Decimal, Decimal], ...]
    gross_proceeds: Decimal | None
    worst_price: Decimal | None
    detail: str


def walk_bids(bids: Sequence[tuple[Decimal, Decimal]], quantity: Decimal, *, min_price: Decimal | None = None,
              truncated: bool = False, market_id: str = "", side: str = "YES") -> SaleWalk:
    """Sell `quantity` into `bids` (ascending (price, size), as stored), best first, never below
    `min_price` (a limit). Bids below the limit are not offered to the walk."""
    eligible = [(p, s) for p, s in bids if s > 0 and (min_price is None or p >= min_price)]
    # A limit hides the deeper bids, so running out is a real shortfall, not unknown depth.
    hidden_by_limit = min_price is not None and len(eligible) < len([b for b in bids if b[1] > 0])
    mirror = DepthLadder("kalshi", market_id, "NO" if side == "YES" else "YES",
                         tuple(DepthLevel(Decimal(1) - p, s) for p, s in sorted(eligible, reverse=True)),
                         truncated and not hidden_by_limit, None, None, None)
    fill = walk_ladder(mirror, quantity)
    if fill.status is not DepthStatus.FILLABLE:
        return SaleWalk(fill.status, fill.quantity, fill.available, (), None, None, fill.detail)
    levels = tuple((Decimal(1) - t.price, t.size) for t in fill.takes)
    return SaleWalk(fill.status, fill.quantity, fill.available, levels, fill.quantity - fill.gross_cost,
                    Decimal(1) - fill.limit_price, fill.detail)


def depth_at_or_above(bids: Sequence[tuple[Decimal, Decimal]], price: Decimal) -> Decimal:
    return sum((s for p, s in bids if p >= price), Decimal(0))


# --------------------------------------------------------------------------- trading state


class TradingState(str, Enum):
    OPEN = "OPEN"
    TRADING_PAUSED = "TRADING_PAUSED"  # docs: placement blocked, cancellation still available
    EXCHANGE_PAUSED = "EXCHANGE_PAUSED"  # docs: placement and cancellation both blocked
    MARKET_CLOSED = "MARKET_CLOSED"
    UNKNOWN = "UNKNOWN"


def trading_state(exchange_status: Mapping[str, Any] | None, market_status: str | None) -> TradingState:
    """From `GET /exchange/status` (`exchange_active`, `trading_active`) and the market's own status
    word. A missing or non-boolean field is UNKNOWN, never OPEN."""
    if not isinstance(exchange_status, Mapping):
        return TradingState.UNKNOWN
    exchange, trading = exchange_status.get("exchange_active"), exchange_status.get("trading_active")
    if exchange is False:
        return TradingState.EXCHANGE_PAUSED
    if trading is False:
        return TradingState.TRADING_PAUSED
    if exchange is not True or trading is not True or not isinstance(market_status, str):
        return TradingState.UNKNOWN
    if market_status.lower() in ("active", "open"):
        return TradingState.OPEN
    return TradingState.MARKET_CLOSED


# --------------------------------------------------------------------------- game state


class GameStateStatus(str, Enum):
    OBSERVED = "OBSERVED"
    UNSUPPORTED_OR_UNMAPPED = "UNSUPPORTED_OR_UNMAPPED"  # docs: null for unsupported / no Sportradar id
    PARSE_FAILED = "PARSE_FAILED"


@dataclass(frozen=True)
class GameState:
    """One game-state observation. Every field is optional: None is UNKNOWN, never 0."""

    game_id: str
    source_id: str
    source_event_id: str | None  # the source's id for this update; corrections reuse or link it
    stamps: Stamps
    status: GameStateStatus
    raw_sha256: str
    home_score: int | None = None
    away_score: int | None = None
    period: str | None = None
    game_clock_text: str | None = None  # "Q4 02:13" is game time, not UTC
    possession: str | None = None
    down_distance: str | None = None
    field_position: str | None = None
    game_status: str | None = None
    finality: OutcomeFinality = OutcomeFinality.UNKNOWN
    corrects: str | None = None  # `observation_id` of the observation this one corrects

    @property
    def observation_id(self) -> str:
        return _sha({"game": self.game_id, "source": self.source_id, "event": self.source_event_id,
                     "raw": self.raw_sha256, "first": self.stamps.first_observed_utc})[:24]

    def content(self) -> tuple:
        return (self.home_score, self.away_score, self.period, self.game_clock_text, self.possession,
                self.down_distance, self.field_position, self.game_status, self.finality)


def game_state_from_payload(game_id: str, payload: Any, *, source_id: str, receipt_utc: str,
                            source_event_id: str | None = None, field_map: Mapping[str, str] | None = None
                            ) -> GameState:
    """A game-state observation from a decoded source payload.

    `field_map` names which payload key feeds which field; it is supplied per source after the
    source's real schema is verified. With no map, nothing is read: the Kalshi game_stats schema
    does not document score, clock or possession fields, and this code does not guess them. A
    null payload is UNSUPPORTED_OR_UNMAPPED."""
    stamps = Stamps(receipt_utc=receipt_utc, first_observed_utc=receipt_utc)
    digest = _sha(payload)
    if payload is None:
        return GameState(game_id, source_id, source_event_id, stamps, GameStateStatus.UNSUPPORTED_OR_UNMAPPED, digest)
    if not isinstance(payload, Mapping):
        return GameState(game_id, source_id, source_event_id, stamps, GameStateStatus.PARSE_FAILED, digest)
    values: dict[str, Any] = {}
    for target, key in (field_map or {}).items():
        v = payload.get(key)
        if target in ("home_score", "away_score"):
            values[target] = v if isinstance(v, int) and not isinstance(v, bool) and v >= 0 else None
        elif target == "finality":
            values[target] = OutcomeFinality(v) if v in {f.value for f in OutcomeFinality} else OutcomeFinality.UNKNOWN
        elif target in GameState.__dataclass_fields__:
            values[target] = v if isinstance(v, str) and v else None
    return GameState(game_id, source_id, source_event_id, stamps, GameStateStatus.OBSERVED, digest, **values)


class JournalEntry(str, Enum):
    NEW = "NEW"
    DUPLICATE = "DUPLICATE"  # same source event and content: kept, first observation unchanged
    CORRECTION = "CORRECTION"  # same source event, new content: appended, linked, nothing overwritten


@dataclass(frozen=True)
class GameJournal:
    """Append-only game-state observations of one game, in arrival order."""

    game_id: str
    entries: tuple[tuple[JournalEntry, GameState], ...] = ()

    def append(self, obs: GameState) -> "GameJournal":
        if obs.game_id != self.game_id:
            raise ValueError(f"observation is for {obs.game_id}, journal is {self.game_id}")
        kind = JournalEntry.NEW
        if obs.source_event_id is not None:
            prior = [s for k, s in self.entries if k is not JournalEntry.DUPLICATE
                     and s.source_event_id == obs.source_event_id and s.source_id == obs.source_id]
            if prior:
                latest = prior[-1]
                if latest.content() == obs.content():
                    kind = JournalEntry.DUPLICATE
                else:
                    kind = JournalEntry.CORRECTION
                    obs = replace(obs, corrects=latest.observation_id)
        return replace(self, entries=self.entries + ((kind, obs),))


def game_state_as_of(journal: GameJournal, as_of: datetime | str) -> GameState | None:
    """What we had actually seen at `as_of`: the newest non-duplicate observation whose
    first-observed time is at or before it. A later correction is invisible before it arrived."""
    at = parse_utc(as_of)
    if at is None:
        raise ValueError("as_of must be timezone-aware")
    seen = [s for kind, s in journal.entries
            if kind is not JournalEntry.DUPLICATE and parse_utc(s.stamps.first_observed_utc) <= at]
    return max(seen, key=lambda s: parse_utc(s.stamps.first_observed_utc)) if seen else None


# --------------------------------------------------------------------------- failures and coverage


class FailureKind(str, Enum):
    CONNECT_FAILED = "CONNECT_FAILED"
    DISCONNECTED = "DISCONNECTED"
    HTTP_429 = "HTTP_429"
    HTTP_ERROR = "HTTP_ERROR"
    TIMEOUT = "TIMEOUT"
    PARSE_ERROR = "PARSE_ERROR"
    SHUTDOWN = "SHUTDOWN"


@dataclass(frozen=True)
class SourceFailure:
    kind: FailureKind
    at_utc: str
    detail: str


@dataclass(frozen=True)
class CoverageReport:
    """How much of a window had a usable book. Unusable time is reported, never dropped."""

    market_ticker: str
    window_start_utc: str
    window_end_utc: str
    usable_seconds: Decimal
    unusable_seconds_by_reason: tuple[tuple[str, Decimal], ...]
    gaps: int
    resyncs: int
    duplicates: int
    ignored_before_start: int
    failures: tuple[SourceFailure, ...]
    parse_failures: int
    contract_version: str = CONTRACT_VERSION

    @property
    def coverage_fraction(self) -> Decimal | None:
        total = self.usable_seconds + sum((s for _, s in self.unusable_seconds_by_reason), Decimal(0))
        return None if total <= 0 else (self.usable_seconds / total).quantize(Decimal("0.0001"))


def coverage_report(market_ticker: str, transitions: Sequence[Transition], *, window_start: datetime | str,
                    window_end: datetime | str, max_silence: timedelta,
                    failures: Sequence[SourceFailure] = (), parse_failures: int = 0) -> CoverageReport:
    """Usable time in [window_start, window_end]. A VALID book counts as usable only up to
    `max_silence` after the last message received on it: a quiet feed cannot be told apart from a
    dead one without liveness evidence, so silence beyond that is SILENT_UNKNOWN."""
    start, end = parse_utc(window_start), parse_utc(window_end)
    if start is None or end is None or end <= start:
        raise ValueError("window needs timezone-aware start < end")
    buckets: dict[str, Decimal] = {}
    usable = Decimal(0)
    timeline = [(parse_utc(t.state.last_receipt_utc), t.state.status) for t in transitions]
    points = [(start, BookStatus.NO_VALID_START)] + [(at, s) for at, s in timeline if at is not None]
    points.sort(key=lambda p: p[0])
    status_at, last_msg = BookStatus.NO_VALID_START, None
    cursor = start
    for at, status in points + [(end, None)]:
        at = min(max(at, start), end)
        if at > cursor:
            span_start = cursor
            if status_at is BookStatus.VALID and last_msg is not None:
                live_until = min(at, max(span_start, last_msg + max_silence))
                live = Decimal(str((live_until - span_start).total_seconds())) if live_until > span_start else Decimal(0)
                usable += live
                rest = Decimal(str((at - span_start).total_seconds())) - live
                if rest > 0:
                    buckets["SILENT_UNKNOWN"] = buckets.get("SILENT_UNKNOWN", Decimal(0)) + rest
            else:
                key = status_at.value
                buckets[key] = buckets.get(key, Decimal(0)) + Decimal(str((at - span_start).total_seconds()))
            cursor = at
        if status is not None:
            status_at, last_msg = status, at
    counts = transitions[-1].state if transitions else BookState(market_ticker)
    return CoverageReport(
        market_ticker, start.isoformat(), end.isoformat(), usable, tuple(sorted(buckets.items())),
        gaps=counts.count(Applied.GAP_DETECTED) + counts.count(Applied.DELTA_WITHOUT_SEQ),
        resyncs=counts.count(Applied.RESYNCED), duplicates=counts.count(Applied.IGNORED_DUPLICATE),
        ignored_before_start=counts.count(Applied.IGNORED_BEFORE_START),
        failures=tuple(f for f in failures if start <= (parse_utc(f.at_utc) or start) <= end),
        parse_failures=parse_failures)


# --------------------------------------------------------------------------- file transport (the only one)


@dataclass(frozen=True)
class JournalLine:
    """One line of a JSONL journal: a message, a failure, or a game-state payload."""

    line_no: int
    receipt_utc: str
    kind: str  # "book" | "failure" | "game_state"
    body: Any
    data_kind: DataKind
    extra: Mapping[str, Any] = field(default_factory=dict)


def read_journal(path: Path) -> Iterator[JournalLine]:
    """Read a local JSONL journal. This is the only transport in v1: no socket, no HTTP.

    The first line is a header `{"journal": "inplay-journal-v1", "data_kind": "SYNTHETIC" |
    "FIXTURE" | "RECORDED", ...}`. Every later line is `{"receipt_utc", "kind", "body", ...}`.
    A malformed line is yielded as a `failure` of kind PARSE_ERROR, never skipped."""
    with Path(path).open("r", encoding="utf-8") as handle:
        header_line = handle.readline()
        try:
            header = json.loads(header_line)
        except json.JSONDecodeError:
            raise ValueError(f"{path}: the first line is not a journal header") from None
        if not isinstance(header, Mapping) or header.get("journal") != "inplay-journal-v1":
            raise ValueError(f"{path}: not an inplay-journal-v1 file")
        data_kind = DataKind(header.get("data_kind"))
        for n, line in enumerate(handle, start=2):
            if not line.strip():
                continue
            try:
                row = json.loads(line)
                receipt = row["receipt_utc"]
                if parse_utc(receipt) is None:
                    raise ValueError("receipt_utc is not timezone-aware")
                kind = row["kind"]
                if kind not in ("book", "failure", "game_state"):
                    raise ValueError(f"unknown kind {kind!r}")
                yield JournalLine(n, receipt, kind, row.get("body"), data_kind,
                                  {k: v for k, v in row.items() if k not in ("receipt_utc", "kind", "body")})
            except (json.JSONDecodeError, KeyError, TypeError, ValueError) as exc:
                yield JournalLine(n, "", "failure", {"kind": FailureKind.PARSE_ERROR.value, "detail": str(exc)},
                                  data_kind)


def replay_book_journal(path: Path, market_ticker: str) -> tuple[BookState, tuple[Transition, ...],
                                                                   tuple[SourceFailure, ...], int, DataKind]:
    """Reconstruct one market's book from a journal file: (final state, transitions, failures,
    parse failures, data kind). Failures and parse errors are returned, not dropped."""
    state, transitions, failures, parse_failures = BookState(market_ticker), [], [], 0
    data_kind = DataKind.SYNTHETIC
    for line in read_journal(path):
        data_kind = line.data_kind
        if line.kind == "failure":
            body = line.body if isinstance(line.body, Mapping) else {}
            try:
                kind = FailureKind(body.get("kind"))
            except ValueError:
                kind = FailureKind.PARSE_ERROR
            if kind is FailureKind.PARSE_ERROR:
                parse_failures += 1
            failures.append(SourceFailure(kind, line.receipt_utc, str(body.get("detail", ""))))
            continue
        if line.kind != "book":
            continue
        msg = parse_book_message(line.body, receipt_utc=line.receipt_utc,
                                 first_observed_utc=line.extra.get("first_observed_utc"),
                                 processing_utc=line.extra.get("processing_utc"))
        if isinstance(msg, ParseFailure):
            parse_failures += 1
            failures.append(SourceFailure(FailureKind.PARSE_ERROR, line.receipt_utc, f"{msg.reason}: {msg.detail}"))
            continue
        if msg.market_ticker != market_ticker:
            continue
        t = apply_message(state, msg)
        transitions.append(t)
        state = t.state
    return state, tuple(transitions), tuple(failures), parse_failures, data_kind
