"""Descriptive forecast-vs-settlement statistics for EXP-001, TRAIN SPLIT ONLY.

    python scripts/describe_exp001_train.py            # write gate3/DESCRIPTIVE_TRAIN.md
    python scripts/describe_exp001_train.py --check    # fail if the committed file is stale

Reads the committed dataset, keeps rows whose split is "train", and never reads the
forecast or label of a validation or test row: those rows are dropped before any value
is parsed, and `describe` itself refuses non-train rows. No thresholds, windows or model
variants are searched here.
"""

from __future__ import annotations

import argparse
import csv
import io
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from edge_lab.describe_exp001 import describe  # noqa: E402

GATE3 = ROOT / "experiments" / "EXP-001-kxhighny-nws-vs-market" / "gate3"


def train_rows(csv_text: str) -> list[dict]:
    return [r for r in csv.DictReader(io.StringIO(csv_text)) if r["split"] == "train"]


def _table(summary: dict) -> list[str]:
    keys = ("n", "mean", "median", "sd", "mae", "rmse", "exact_pct", "within_1_pct",
            "within_2_pct", "within_3_pct", "p05", "p95", "min", "max")
    return ["| " + " | ".join(keys) + " |", "|" + "---|" * len(keys),
            "| " + " | ".join(str(summary.get(k, "")) for k in keys) + " |"]


def render(result: dict, dataset_sha256: str) -> str:
    lines = [
        "# EXP-001 descriptive analysis: TRAIN split only (generated)",
        "",
        f"Generated by `scripts/describe_exp001_train.py` from dataset SHA-256 `{dataset_sha256}`.",
        f"Scope: {result['scope']}. Error e = {result['error_definition']}.",
        "Validation (2023-2024) and test (2025-2026) forecast errors were **not computed**.",
        "This describes the forecast process; it is not a model result and not a trading result.",
        "",
        "## Overall",
        "",
        *_table(result["overall"]),
        "",
        "## Error distribution (e: days)",
        "",
        "| e (°F) | days |",
        "|---|---|",
        *[f"| {k} | {v} |" for k, v in result["distribution"].items()],
        "",
        "## By meteorological season",
        "",
        "| season | n | mean | sd | mae | exact_pct | within_2_pct |",
        "|---|---|---|---|---|---|---|",
        *[
            f"| {s} | {v['n']} | {v.get('mean')} | {v.get('sd')} | {v.get('mae')} | "
            f"{v.get('exact_pct')} | {v.get('within_2_pct')} |"
            for s, v in result["by_season"].items()
        ],
        "",
        "## Revision (issuance >= 12 h before the chosen one vs the chosen one)",
        "",
        f"`{json.dumps(result['revision'], sort_keys=True)}`",
        "",
        "## Power inputs (in-sample on train; sizing only, selects nothing; see POWER.md)",
        "",
        f"`{json.dumps(result['power_inputs'], sort_keys=True)}`",
        "",
        "## Bracket boundary",
        "",
        f"`{json.dumps(result['bracket_boundary'], sort_keys=True)}`",
        "",
        "Pairs are taken as even-start (80-81, 82-83, ...). Captured Kalshi `between` markets use",
        "both even-start and odd-start 2°F pairs, so this is an illustration of how often a",
        "point forecast misses a 2°F bin, not the rate for any particular event.",
        "",
        "## Observations (no parameters were chosen from them)",
        "",
        "- The error distribution is not symmetric: its right tail is longer than its left.",
        "  One structural candidate: the PFM daytime maximum covers 7 AM-7 PM local standard",
        "  time, while the CLI maximum covers the whole calendar day in local standard time, so",
        "  warm nights and mid-night frontal passages can set a higher daily maximum.",
        "  This is a hypothesis, not a finding.",
        "- Seasonal differences in bias and spread exist on train. The preregistered V2",
        "  (seasonal) variant is chosen only by the validation rule in DESIGN.md §5, never",
        "  from this table.",
        "- The baseline uses an empirical error pmf, so it needs no symmetry or normality",
        "  assumption. The Gaussian R1 is a reported reference only.",
        "",
    ]
    return "\n".join(lines)


def build() -> str:
    csv_text = (GATE3 / "dataset.csv").read_text(encoding="utf-8")
    manifest = json.loads((GATE3 / "dataset_manifest.json").read_text(encoding="utf-8"))
    return render(describe(train_rows(csv_text)), manifest["dataset_sha256"])


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    content = build()
    target = GATE3 / "DESCRIPTIVE_TRAIN.md"
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            print("stale DESCRIPTIVE_TRAIN.md (run scripts/describe_exp001_train.py)")
            return 1
        return 0
    target.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
